### PR TITLE
adding go unit tests to the workflow

### PR DESCRIPTION
**Pull request by vishnuchalla**
## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

- Related Issue # https://github.com/cloud-bulldozer/go-commons/issues/12
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
Tested through the CI

### CODE REVIEW

**Comment by vishnuchalla** [comment]
@shashank-boyapally indexers tests seems to be flaky. Requesting to take a look. Thank you

**Comment by shashank-boyapally** [comment]
The reason this has happened is as we randomized the tests(all in context of local.go), sometimes Index() is being called before new() which is seldom in a real world situation, but in order to mitigate this problem I've taken care of creating the placeholder dir whenever Index is being called by which this unexpected error can be avoided. Please look into the changes, Thank you.

**Review by chentex — COMMENTED** [review]
I see all the code good, the only thing I see weird is that merge to main commit that you have, `fae7f3727b332f27e72aeb44ef6d53604846845e`, maybe you need to rebase your working branch.

**Comment by vishnuchalla** [comment]
> I see all the code good, the only thing I see weird is that merge to main commit that you have, `fae7f3727b332f27e72aeb44ef6d53604846845e`, maybe you need to rebase your working branch.

I tried rebasing but there seems to be having lot many conflicts. So opened up a new one: https://github.com/cloud-bulldozer/go-commons/pull/20

**Pull request closed without merging**
