### PR TITLE
adding go unit tests to the workflow

### PR DESCRIPTION
**Pull request by vishnuchalla**
## Type of change

- [ ] Refactor
- [x] New feature
- [ ] Bug fix
- [ ] Optimization
- [ ] Documentation Update

## Related Tickets & Documents

- Related Issue # https://github.com/cloud-bulldozer/go-commons/issues/12
- Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Testing
Tested through CI.

### CODE REVIEW

**Review by chentex — APPROVED** [review]
/LGTM

**Comment by shashank-boyapally** [comment]
Request to please merge the Bug Fixes before this PR, here all checks are passed because one of the test (test 3 of QueryStringStats()) is running after some tests, if it runs first then the test fails, this issue is fixed in the PR #21 . TYIA. Other than that Awesome Work🚀. LGTM.

**Review by shashank-boyapally — APPROVED** [review]

**Review by jtaleric — APPROVED** [review]
lgtm!

**Review by rsevilla87 — APPROVED** [review]
lgtm

**Pull request merged**
